$env:SPRING_PROFILES_ACTIVE="demo"
$env:PREMIUM_SMOKE_ENABLED="false"
$env:MATCHER_OBSERVABILITY_ENABLED="false"
$env:RETENTION_DAILY_PICKS_ENABLED="false"
$env:RETENTION_NOTIFICATIONS_ENABLED="false"
$env:RETENTION_NOTIFICATIONS_SEND_BOOST="false"
$env:RETENTION_NOTIFICATIONS_SEND_REWIND="false"
$env:LOGGING_LEVEL_ROOT="WARN"

docker compose up -d --build backend
